# build.ps1
$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$libDir = Join-Path $scriptDir "lib"
$outFile = Join-Path $scriptDir "sb.sh"

if (-not (Test-Path $libDir)) {
    Write-Error "lib/ directory not found: $libDir"
    exit 1
}

# Get all .sh files starting with digits and sort by name
$files = Get-ChildItem -Path $libDir -Filter "*.sh" |
    Where-Object { $_.Name -match '^\d' } |
    Sort-Object Name

if ($files.Count -eq 0) {
    Write-Error "No module files found in $libDir"
    exit 1
}

Write-Host "Found $($files.Count) module files" -ForegroundColor Cyan

$sb = [System.Text.StringBuilder]::new()
$null = $sb.Append("#!/usr/bin/env bash`n")
$null = $sb.Append("`n")
$null = $sb.Append("# ============================================================`n")
$null = $sb.Append("# Sing-box Elite Management System`n")
$null = $sb.Append("# Auto-generated by build script. Do not edit directly.`n")
$null = $sb.Append("# Source code is in lib/ directory.`n")
$null = $sb.Append("# ============================================================`n")
$null = $sb.Append("`n")

foreach ($file in $files) {
    $fname = $file.Name
    Write-Host "  Processing: $fname" -ForegroundColor Gray
    $raw = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
    # Normalize to LF
    $raw = $raw -replace "`r`n", "`n"
    $lines = $raw -split "`n"

    $null = $sb.Append("`n# >>>>>>>>> BEGIN MODULE: $fname <<<<<<<<<<<`n")

    $first = $true
    foreach ($line in $lines) {
        if ($first) {
            $first = $false
            if ($line -match "^#!") { continue }
        }
        $null = $sb.Append($line + "`n")
    }

    $null = $sb.Append("`n# >>>>>>>>> END MODULE: $fname <<<<<<<<<<<`n")
}

$content = $sb.ToString()
# Ensure pure LF
$content = $content -replace "`r`n", "`n"

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($outFile, $content, $utf8NoBom)

# Extract version
$version = "unknown"
if ($content -match 'SCRIPT_VERSION="([^"]+)"') {
    $version = $Matches[1]
}
$lineCount = ($content -split "`n").Count

Write-Host ""
Write-Host "[OK] Build complete: $outFile" -ForegroundColor Green
Write-Host "     Version: $version" -ForegroundColor Green
Write-Host "     Lines: $lineCount" -ForegroundColor Green
